eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8060